[project]
name = "workshop1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eyad-Baher", email = "eaydbaher69@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
workshop1 = "workshop1:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
